version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "8000:80"
    environment:
      POSTGRES_USER: "sa"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_PORT: "8001"
  database:
    image: postgres:alpine
    ports:
      - "8001:5432"
    environment:
      POSTGRES_USER: "sa"
      POSTGRES_PASSWORD: "pass"