version: "3.9"

services:
  api:
    depends_on:
      database:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      API_POSTGRES__HOST: database
      API_POSTGRES__USER: ${POSTGRES_USER}
      API_POSTGRES__PASSWORD: ${POSTGRES_PASSWORD}
      API_POSTGRES__PORT: 5432
      API_JWT__SECRET: ${API_JWT__SECRET}
      API_JWT__ISSUER: ${API_JWT__ISSUER}
  database:
    image: postgres:alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 15s
      retries: 10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
volumes:
  db-data:
    driver: local